---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
non-functional:
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен иметь мобильную версию.
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
implicit:
  - Пользователь должен иметь возможность регистрации и авторизации на сайте.
  - На странице со списком товаров должна присутствовать постраничная навигация для удобства.
  - Список производителей не должен меняться при перенаправлении на другую страницу списка товаров.
  - После нажатия на кнопку 'Оформить заказ' на странице заказа товаров, заказанные товары должны должны быть определены в отдельную форму "Заказ №...".
  - Товары из сделанного заказа должны автоматически удаляться из корзины.
  - Пользователь должен иметь возможность удаления товара из корзины.
  - Сайт должен иметь функциональность оплаты товара.
  - Пользователь должен иметь возможность оплатить товар картой платежных систем Visa, Mastercard, МИР.
  - При нажатии на любое изображение товара в описании товара, оно должно выводиться на экран.
