---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
non-functional:
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен иметь мобильную версию.
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
implicit:
  - Пользователь должен иметь возможность регистрации на сайте
  - Пользователь должен иметь возможность авторизации на сайте
  - В футере сайта должна отображаться информация о физическом или юридическом лице, которое осуществляет продажу: наименование, юридический адрес, сведение о постановке на налоговый учет, контакт для обратной связи(эл. почта или телефон).
  - Должна быть персонализация (контактная информация) о покупателе, чтобы была возможность с ним связаться в случае непридвиденных проблем либо уточнения заказа.
  - На странице с товарами должно присутствовать постраничное перенаправление для удобства.
  - Список производителей не должен меняться при перенаправлении на другую страницу списка товаров.
  - После нажатия на кнопку 'Оформить заказ' на странице заказа товаров, заказанные товары должны должны быть определены в отдельную форму "Заказ №...".
  - Ранее заказанные товары не должны учитываться при суммировании последующих заказов.
  - Пользователь должен иметь возможность удаления товара из корзины.
  - Список производителей должен быть в алфавитном порядке.
  - Карточка товара при изменении языка должны быть полностью переведена на соответствующий язык.
  - Сайт должен иметь функциональность оплаты товара.
  - Пользователь должен иметь возможность оплатить товар картой платежных систем Visa, Mastercard, МИР
  - Значения выпадающего списка "Категория" должны быть в алфавитном порядке.
  - Фильтрация товаров должна включать функциональность "Цена: по убывающей/по возрастающей".
  - При нажатии на любое изображение товара в описании товара, оно должно выводиться на экран.
