---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
non-functional:
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен иметь мобильную версию.
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
implicit:
  - Пользователь должен иметь возможность регистрации и авторизации на сайте
  - Пользователь должен иметь возможность фильтровать товар по производителям
  - Пользователь должен иметь возможность просмотра истории заказов
  - Пользователь должен иметь возможность удаления товара из корзины.
  - Сайт должен иметь кнопки навигации 
  - Корзина должна очищаться после совершения заказа
  - Сайт должен иметь функциональность оплаты товара.
  - Карточка товара должна корректно отбражать изображения и описание
